[theme]
base = "dark"
primaryColor = "#E12E2E"
backgroundColor = "#111111"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#FFFFFF"
linkColor = "#E12E2E"
font = "Montserrat:https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap, sans-serif"
headingFont = "Montserrat:https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap, sans-serif"
baseFontSize = 16
baseFontWeight = 400
headingFontSizes = ["2.625rem", "1.375rem", "1.375rem", "1.375rem", "1.375rem", "1.375rem"]
headingFontWeights = [900, 700, 700, 700, 700, 700]
baseRadius = "none"
buttonRadius = "none"

[theme.sidebar]
backgroundColor = "#0A0A0A"
secondaryBackgroundColor = "#1E1E1E"
